services:
  # Nginx 服务
#  nginx:
#    image: nginx:alpine
#    container_name: edgeflow-nginx
#    ports:
#      - "80:80"   # 映射 HTTP 端口
#      - "443:443" # 如果有 SSL，开启此端口
#    volumes:
#      - ./nginx/edgeflow.conf:/etc/nginx/conf.d/default.conf:ro
#      - ./static:/app/static:ro # 🌟 关键：让 Nginx 也能读取音频文件目录
#      - ./logs/nginx:/var/log/nginx
#    depends_on:
#      - edgeflow-app
#    networks:
#      - edgeflow-net
  #后端服务
  edgeflow-app:
    # 🌟 关键：告诉 compose 从当前目录构建镜像
    build: .
    image: edgeflow:latest
    container_name: edgeflow
    ports:
      - "12180:12180" # 屏蔽外部直接访问，只通过 Nginx 访问
    volumes:
      - ./conf:/app/edgeflow/conf
    restart: always
    networks:
      - edgeflow-net
    environment:
      KAFKA_HOST: 43.156.94.29
      KAFKA_PORT: 9092
      REDIS_HOST: 43.156.94.29
      REDIS_PORT: 6379
      REDIS_PASSWORD: Yang308719@#
      DB_HOST: 43.156.94.29
      DB_PORT: 3306
      DB_USER: edgeflow_user
      DB_PASSWORD: Yang308719@#
      DB_NAME: strategy_db
      TEST: ""

networks:
  edgeflow-net:
    driver: bridge