// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: market_data.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- 消息级别 ---
type AlertLevel int32

const (
	AlertLevel_ALERT_LEVEL_INFO     AlertLevel = 0 // 普通信息
	AlertLevel_ALERT_LEVEL_WARNING  AlertLevel = 1 // 警告
	AlertLevel_ALERT_LEVEL_CRITICAL AlertLevel = 2 // 严重/致命
)

// Enum value maps for AlertLevel.
var (
	AlertLevel_name = map[int32]string{
		0: "ALERT_LEVEL_INFO",
		1: "ALERT_LEVEL_WARNING",
		2: "ALERT_LEVEL_CRITICAL",
	}
	AlertLevel_value = map[string]int32{
		"ALERT_LEVEL_INFO":     0,
		"ALERT_LEVEL_WARNING":  1,
		"ALERT_LEVEL_CRITICAL": 2,
	}
)

func (x AlertLevel) Enum() *AlertLevel {
	p := new(AlertLevel)
	*p = x
	return p
}

func (x AlertLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_market_data_proto_enumTypes[0].Descriptor()
}

func (AlertLevel) Type() protoreflect.EnumType {
	return &file_market_data_proto_enumTypes[0]
}

func (x AlertLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertLevel.Descriptor instead.
func (AlertLevel) EnumDescriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{0}
}

// --- 消息类型 ---
type AlertType int32

const (
	AlertType_ALERT_TYPE_SYSTEM   AlertType = 0 // 系统公告，如“维护通知”
	AlertType_ALERT_TYPE_PRICE    AlertType = 1 // 行情类提醒，如价格突破
	AlertType_ALERT_TYPE_STRATEGY AlertType = 2 // 策略信号类提醒
	AlertType_ALERT_TYPE_CUSTOM   AlertType = 3 // 用户自定义提醒
	// 🚀 新增的核心业务提醒类型
	AlertType_ALERT_TYPE_LISTING  AlertType = 4 // 交易对上新/下架/调整
	AlertType_ALERT_TYPE_ON_CHAIN AlertType = 5 // 链上提醒，如鲸鱼转移、大额稳定币铸造
	AlertType_ALERT_TYPE_SOCIAL   AlertType = 6 // 社交媒体提醒，如大V提及
)

// Enum value maps for AlertType.
var (
	AlertType_name = map[int32]string{
		0: "ALERT_TYPE_SYSTEM",
		1: "ALERT_TYPE_PRICE",
		2: "ALERT_TYPE_STRATEGY",
		3: "ALERT_TYPE_CUSTOM",
		4: "ALERT_TYPE_LISTING",
		5: "ALERT_TYPE_ON_CHAIN",
		6: "ALERT_TYPE_SOCIAL",
	}
	AlertType_value = map[string]int32{
		"ALERT_TYPE_SYSTEM":   0,
		"ALERT_TYPE_PRICE":    1,
		"ALERT_TYPE_STRATEGY": 2,
		"ALERT_TYPE_CUSTOM":   3,
		"ALERT_TYPE_LISTING":  4,
		"ALERT_TYPE_ON_CHAIN": 5,
		"ALERT_TYPE_SOCIAL":   6,
	}
)

func (x AlertType) Enum() *AlertType {
	p := new(AlertType)
	*p = x
	return p
}

func (x AlertType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertType) Descriptor() protoreflect.EnumDescriptor {
	return file_market_data_proto_enumTypes[1].Descriptor()
}

func (AlertType) Type() protoreflect.EnumType {
	return &file_market_data_proto_enumTypes[1]
}

func (x AlertType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertType.Descriptor instead.
func (AlertType) EnumDescriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{1}
}

// Ticker 数据 (价格网关使用)
type TickerUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstId        string                 `protobuf:"bytes,1,opt,name=inst_id,json=instId,proto3" json:"inst_id,omitempty"`            // 币种符号，例如 BTC-USDT
	LastPrice     string                 `protobuf:"bytes,2,opt,name=last_price,json=lastPrice,proto3" json:"last_price,omitempty"`   // 最新成交价格
	Vol_24H       string                 `protobuf:"bytes,3,opt,name=vol_24h,json=vol24h,proto3" json:"vol_24h,omitempty"`            // 24小时成交量 (单位币)
	VolCcy_24H    string                 `protobuf:"bytes,4,opt,name=vol_ccy_24h,json=volCcy24h,proto3" json:"vol_ccy_24h,omitempty"` // 24小时成交额 (单位计价币)
	High_24H      string                 `protobuf:"bytes,5,opt,name=high_24h,json=high24h,proto3" json:"high_24h,omitempty"`         // 24小时最高价
	Low_24H       string                 `protobuf:"bytes,6,opt,name=low_24h,json=low24h,proto3" json:"low_24h,omitempty"`            // 24小时最低价
	Open_24H      string                 `protobuf:"bytes,7,opt,name=open_24h,json=open24h,proto3" json:"open_24h,omitempty"`         // 24小时开盘价格
	Change_24H    float64                `protobuf:"fixed64,8,opt,name=change_24h,json=change24h,proto3" json:"change_24h,omitempty"` // 24小时涨跌幅（%）
	AskPx         string                 `protobuf:"bytes,9,opt,name=ask_px,json=askPx,proto3" json:"ask_px,omitempty"`               // 卖一价
	AskSz         string                 `protobuf:"bytes,10,opt,name=ask_sz,json=askSz,proto3" json:"ask_sz,omitempty"`              // 卖一量
	BidPx         string                 `protobuf:"bytes,11,opt,name=bid_px,json=bidPx,proto3" json:"bid_px,omitempty"`              // 买一价
	BidSz         string                 `protobuf:"bytes,12,opt,name=bid_sz,json=bidSz,proto3" json:"bid_sz,omitempty"`              // 买一量
	Ts            int64                  `protobuf:"varint,13,opt,name=ts,proto3" json:"ts,omitempty"`                                // 时间戳 (毫秒级)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TickerUpdate) Reset() {
	*x = TickerUpdate{}
	mi := &file_market_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickerUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickerUpdate) ProtoMessage() {}

func (x *TickerUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickerUpdate.ProtoReflect.Descriptor instead.
func (*TickerUpdate) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{0}
}

func (x *TickerUpdate) GetInstId() string {
	if x != nil {
		return x.InstId
	}
	return ""
}

func (x *TickerUpdate) GetLastPrice() string {
	if x != nil {
		return x.LastPrice
	}
	return ""
}

func (x *TickerUpdate) GetVol_24H() string {
	if x != nil {
		return x.Vol_24H
	}
	return ""
}

func (x *TickerUpdate) GetVolCcy_24H() string {
	if x != nil {
		return x.VolCcy_24H
	}
	return ""
}

func (x *TickerUpdate) GetHigh_24H() string {
	if x != nil {
		return x.High_24H
	}
	return ""
}

func (x *TickerUpdate) GetLow_24H() string {
	if x != nil {
		return x.Low_24H
	}
	return ""
}

func (x *TickerUpdate) GetOpen_24H() string {
	if x != nil {
		return x.Open_24H
	}
	return ""
}

func (x *TickerUpdate) GetChange_24H() float64 {
	if x != nil {
		return x.Change_24H
	}
	return 0
}

func (x *TickerUpdate) GetAskPx() string {
	if x != nil {
		return x.AskPx
	}
	return ""
}

func (x *TickerUpdate) GetAskSz() string {
	if x != nil {
		return x.AskSz
	}
	return ""
}

func (x *TickerUpdate) GetBidPx() string {
	if x != nil {
		return x.BidPx
	}
	return ""
}

func (x *TickerUpdate) GetBidSz() string {
	if x != nil {
		return x.BidSz
	}
	return ""
}

func (x *TickerUpdate) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

// 批量多个币种的ticker
type TickerBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tickers       []*TickerUpdate        `protobuf:"bytes,1,rep,name=tickers,proto3" json:"tickers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TickerBatch) Reset() {
	*x = TickerBatch{}
	mi := &file_market_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickerBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickerBatch) ProtoMessage() {}

func (x *TickerBatch) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickerBatch.ProtoReflect.Descriptor instead.
func (*TickerBatch) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{1}
}

func (x *TickerBatch) GetTickers() []*TickerUpdate {
	if x != nil {
		return x.Tickers
	}
	return nil
}

// K 线数据 (订阅网关使用)
type WsKlineUpdate struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	InstId        string                   `protobuf:"bytes,1,opt,name=inst_id,json=instId,proto3" json:"inst_id,omitempty"`             // 币种符号
	TimePeriod    string                   `protobuf:"bytes,2,opt,name=time_period,json=timePeriod,proto3" json:"time_period,omitempty"` // K 线周期，例如 "15m"
	Confirm       bool                     `protobuf:"varint,3,opt,name=confirm,proto3" json:"confirm,omitempty"`                        // 是否已收盘
	Data          *WsKlineUpdate_KlineData `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`                               // K 线详细数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WsKlineUpdate) Reset() {
	*x = WsKlineUpdate{}
	mi := &file_market_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WsKlineUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WsKlineUpdate) ProtoMessage() {}

func (x *WsKlineUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WsKlineUpdate.ProtoReflect.Descriptor instead.
func (*WsKlineUpdate) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{2}
}

func (x *WsKlineUpdate) GetInstId() string {
	if x != nil {
		return x.InstId
	}
	return ""
}

func (x *WsKlineUpdate) GetTimePeriod() string {
	if x != nil {
		return x.TimePeriod
	}
	return ""
}

func (x *WsKlineUpdate) GetConfirm() bool {
	if x != nil {
		return x.Confirm
	}
	return false
}

func (x *WsKlineUpdate) GetData() *WsKlineUpdate_KlineData {
	if x != nil {
		return x.Data
	}
	return nil
}

// 错误信息 (所有网关通用)
type ErrorMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`                                                                       // "error"
	Data          map[string]string      `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 通用数据/键值对错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorMessage) Reset() {
	*x = ErrorMessage{}
	mi := &file_market_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMessage) ProtoMessage() {}

func (x *ErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMessage.ProtoReflect.Descriptor instead.
func (*ErrorMessage) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{3}
}

func (x *ErrorMessage) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ErrorMessage) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

// 交易对列表更新 (订阅网关或 Ticker 网关使用)
type InstrumentListUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SortedInstIds []string               `protobuf:"bytes,1,rep,name=sorted_inst_ids,json=sortedInstIds,proto3" json:"sorted_inst_ids,omitempty"` // 排序后的 InstID 列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstrumentListUpdate) Reset() {
	*x = InstrumentListUpdate{}
	mi := &file_market_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstrumentListUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstrumentListUpdate) ProtoMessage() {}

func (x *InstrumentListUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstrumentListUpdate.ProtoReflect.Descriptor instead.
func (*InstrumentListUpdate) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{4}
}

func (x *InstrumentListUpdate) GetSortedInstIds() []string {
	if x != nil {
		return x.SortedInstIds
	}
	return nil
}

// 币种/交易对元数据更新
type InstrumentUpdate struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	NewInstruments      []string               `protobuf:"bytes,1,rep,name=new_instruments,json=newInstruments,proto3" json:"new_instruments,omitempty"`                // 新上架的 InstID 列表
	DelistedInstruments []string               `protobuf:"bytes,2,rep,name=delisted_instruments,json=delistedInstruments,proto3" json:"delisted_instruments,omitempty"` // 已下架的 InstID 列表
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *InstrumentUpdate) Reset() {
	*x = InstrumentUpdate{}
	mi := &file_market_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstrumentUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstrumentUpdate) ProtoMessage() {}

func (x *InstrumentUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstrumentUpdate.ProtoReflect.Descriptor instead.
func (*InstrumentUpdate) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{5}
}

func (x *InstrumentUpdate) GetNewInstruments() []string {
	if x != nil {
		return x.NewInstruments
	}
	return nil
}

func (x *InstrumentUpdate) GetDelistedInstruments() []string {
	if x != nil {
		return x.DelistedInstruments
	}
	return nil
}

// 币种交易所数据
type CryptoExchange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	ApiEndpoint   string                 `protobuf:"bytes,5,opt,name=api_endpoint,json=apiEndpoint,proto3" json:"api_endpoint,omitempty"`
	Country       string                 `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CryptoExchange) Reset() {
	*x = CryptoExchange{}
	mi := &file_market_data_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CryptoExchange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CryptoExchange) ProtoMessage() {}

func (x *CryptoExchange) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CryptoExchange.ProtoReflect.Descriptor instead.
func (*CryptoExchange) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{6}
}

func (x *CryptoExchange) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CryptoExchange) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CryptoExchange) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CryptoExchange) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CryptoExchange) GetApiEndpoint() string {
	if x != nil {
		return x.ApiEndpoint
	}
	return ""
}

func (x *CryptoExchange) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

// 排序列好一组货币id
type SortUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 排序类型
	SortBy string `protobuf:"bytes,1,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	// 使用 repeated 关键字表示一个字符串数组/列表
	SortedInstIds []string `protobuf:"bytes,2,rep,name=sorted_inst_ids,json=sortedInstIds,proto3" json:"sorted_inst_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SortUpdate) Reset() {
	*x = SortUpdate{}
	mi := &file_market_data_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortUpdate) ProtoMessage() {}

func (x *SortUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortUpdate.ProtoReflect.Descriptor instead.
func (*SortUpdate) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{7}
}

func (x *SortUpdate) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *SortUpdate) GetSortedInstIds() []string {
	if x != nil {
		return x.SortedInstIds
	}
	return nil
}

// 加密货币的标签
type CryptoTag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CryptoTag) Reset() {
	*x = CryptoTag{}
	mi := &file_market_data_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CryptoTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CryptoTag) ProtoMessage() {}

func (x *CryptoTag) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CryptoTag.ProtoReflect.Descriptor instead.
func (*CryptoTag) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{8}
}

func (x *CryptoTag) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CryptoTag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CryptoTag) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// 交易数据结构体
type CryptoInstrumentTradingItem struct {
	state              protoimpl.MessageState    `protogen:"open.v1"`
	InstrumentMetadata *CryptoInstrumentMetadata `protobuf:"bytes,1,opt,name=instrument_metadata,json=instrumentMetadata,proto3" json:"instrument_metadata,omitempty"`
	TickerUpdate       *TickerUpdate             `protobuf:"bytes,2,opt,name=ticker_update,json=tickerUpdate,proto3" json:"ticker_update,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CryptoInstrumentTradingItem) Reset() {
	*x = CryptoInstrumentTradingItem{}
	mi := &file_market_data_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CryptoInstrumentTradingItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CryptoInstrumentTradingItem) ProtoMessage() {}

func (x *CryptoInstrumentTradingItem) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CryptoInstrumentTradingItem.ProtoReflect.Descriptor instead.
func (*CryptoInstrumentTradingItem) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{9}
}

func (x *CryptoInstrumentTradingItem) GetInstrumentMetadata() *CryptoInstrumentMetadata {
	if x != nil {
		return x.InstrumentMetadata
	}
	return nil
}

func (x *CryptoInstrumentTradingItem) GetTickerUpdate() *TickerUpdate {
	if x != nil {
		return x.TickerUpdate
	}
	return nil
}

// 一组带有最新价格的币种信息
type CryptoInstrumentTradingArray struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Data          []*CryptoInstrumentTradingItem `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CryptoInstrumentTradingArray) Reset() {
	*x = CryptoInstrumentTradingArray{}
	mi := &file_market_data_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CryptoInstrumentTradingArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CryptoInstrumentTradingArray) ProtoMessage() {}

func (x *CryptoInstrumentTradingArray) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CryptoInstrumentTradingArray.ProtoReflect.Descriptor instead.
func (*CryptoInstrumentTradingArray) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{10}
}

func (x *CryptoInstrumentTradingArray) GetData() []*CryptoInstrumentTradingItem {
	if x != nil {
		return x.Data
	}
	return nil
}

type CryptoInstrumentMetadata struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	InstrumentId   string                 `protobuf:"bytes,2,opt,name=instrument_id,json=instrumentId,proto3" json:"instrument_id,omitempty"`
	ExchangeId     uint32                 `protobuf:"varint,3,opt,name=exchange_id,json=exchangeId,proto3" json:"exchange_id,omitempty"`
	BaseCcy        string                 `protobuf:"bytes,4,opt,name=base_ccy,json=baseCcy,proto3" json:"base_ccy,omitempty"`
	QuoteCcy       string                 `protobuf:"bytes,5,opt,name=quote_ccy,json=quoteCcy,proto3" json:"quote_ccy,omitempty"`
	NameCn         string                 `protobuf:"bytes,6,opt,name=name_cn,json=nameCn,proto3" json:"name_cn,omitempty"`
	NameEn         string                 `protobuf:"bytes,7,opt,name=name_en,json=nameEn,proto3" json:"name_en,omitempty"`
	Status         string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	PricePrecision string                 `protobuf:"bytes,9,opt,name=price_precision,json=pricePrecision,proto3" json:"price_precision,omitempty"` // 价格精度
	QtyPrecision   string                 `protobuf:"bytes,10,opt,name=qty_precision,json=qtyPrecision,proto3" json:"qty_precision,omitempty"`      // 数量精度
	MarketCap      uint64                 `protobuf:"varint,11,opt,name=market_cap,json=marketCap,proto3" json:"market_cap,omitempty"`
	IsContract     bool                   `protobuf:"varint,12,opt,name=is_contract,json=isContract,proto3" json:"is_contract,omitempty"`
	Tags           []*CryptoTag           `protobuf:"bytes,13,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CryptoInstrumentMetadata) Reset() {
	*x = CryptoInstrumentMetadata{}
	mi := &file_market_data_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CryptoInstrumentMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CryptoInstrumentMetadata) ProtoMessage() {}

func (x *CryptoInstrumentMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CryptoInstrumentMetadata.ProtoReflect.Descriptor instead.
func (*CryptoInstrumentMetadata) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{11}
}

func (x *CryptoInstrumentMetadata) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CryptoInstrumentMetadata) GetInstrumentId() string {
	if x != nil {
		return x.InstrumentId
	}
	return ""
}

func (x *CryptoInstrumentMetadata) GetExchangeId() uint32 {
	if x != nil {
		return x.ExchangeId
	}
	return 0
}

func (x *CryptoInstrumentMetadata) GetBaseCcy() string {
	if x != nil {
		return x.BaseCcy
	}
	return ""
}

func (x *CryptoInstrumentMetadata) GetQuoteCcy() string {
	if x != nil {
		return x.QuoteCcy
	}
	return ""
}

func (x *CryptoInstrumentMetadata) GetNameCn() string {
	if x != nil {
		return x.NameCn
	}
	return ""
}

func (x *CryptoInstrumentMetadata) GetNameEn() string {
	if x != nil {
		return x.NameEn
	}
	return ""
}

func (x *CryptoInstrumentMetadata) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CryptoInstrumentMetadata) GetPricePrecision() string {
	if x != nil {
		return x.PricePrecision
	}
	return ""
}

func (x *CryptoInstrumentMetadata) GetQtyPrecision() string {
	if x != nil {
		return x.QtyPrecision
	}
	return ""
}

func (x *CryptoInstrumentMetadata) GetMarketCap() uint64 {
	if x != nil {
		return x.MarketCap
	}
	return 0
}

func (x *CryptoInstrumentMetadata) GetIsContract() bool {
	if x != nil {
		return x.IsContract
	}
	return false
}

func (x *CryptoInstrumentMetadata) GetTags() []*CryptoTag {
	if x != nil {
		return x.Tags
	}
	return nil
}

// --- 提醒/通知消息 ---
// 通常由 AlertService 推送，用于实时通知、价格触发、系统公告等
type AlertMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 基础信息
	Id        string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                           // 唯一ID（UUID）
	Title     string     `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                                                     // 标题，如 “BTC价格突破70000”
	Content   string     `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                                                 // 消息内容，可展示在UI中
	Symbol    string     `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`                                                   // 相关币种（可选）
	Level     AlertLevel `protobuf:"varint,5,opt,name=level,proto3,enum=marketdata.AlertLevel" json:"level,omitempty"`                         // 消息级别（信息、警告、严重）
	AlertType AlertType  `protobuf:"varint,6,opt,name=alert_type,json=alertType,proto3,enum=marketdata.AlertType" json:"alert_type,omitempty"` // 消息类型（价格、系统、策略、自定义等）
	Timestamp int64      `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                            // 服务器时间戳（毫秒）
	// 🚀 路由与追踪字段
	UserId         string `protobuf:"bytes,8,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                          // 接收者 User ID (Kafka Key)
	SubscriptionId string `protobuf:"bytes,10,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"` // 触发此提醒的用户订阅 ID (用于追踪)
	RelatedUrl     string `protobuf:"bytes,11,opt,name=related_url,json=relatedUrl,proto3" json:"related_url,omitempty"`             // 相关链接，如交易哈希或推文链接
	// 可扩展字段，用于自定义展示或行为
	Extra         map[string]string `protobuf:"bytes,9,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 比如 {"trigger_price": "70000", "direction": "up"}
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertMessage) Reset() {
	*x = AlertMessage{}
	mi := &file_market_data_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertMessage) ProtoMessage() {}

func (x *AlertMessage) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertMessage.ProtoReflect.Descriptor instead.
func (*AlertMessage) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{12}
}

func (x *AlertMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AlertMessage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AlertMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AlertMessage) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *AlertMessage) GetLevel() AlertLevel {
	if x != nil {
		return x.Level
	}
	return AlertLevel_ALERT_LEVEL_INFO
}

func (x *AlertMessage) GetAlertType() AlertType {
	if x != nil {
		return x.AlertType
	}
	return AlertType_ALERT_TYPE_SYSTEM
}

func (x *AlertMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AlertMessage) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AlertMessage) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *AlertMessage) GetRelatedUrl() string {
	if x != nil {
		return x.RelatedUrl
	}
	return ""
}

func (x *AlertMessage) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

// --- 通用数据体（服务端 -> 客户端）---
// 这是最终通过 WebSocket 发送给客户端的消息体，包含一个 Oneof 字段
type WebSocketMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 消息的通用类型，用于客户端快速识别
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WebSocketMessage_TickerBatch
	//	*WebSocketMessage_Ticker
	//	*WebSocketMessage_KlineUpdate
	//	*WebSocketMessage_SortUpdate
	//	*WebSocketMessage_ErrorMessage
	//	*WebSocketMessage_InstrumentList
	//	*WebSocketMessage_InstrumentStatusUpdate
	//	*WebSocketMessage_InstrumentMetadata
	//	*WebSocketMessage_InstrumentTradingList
	//	*WebSocketMessage_AlertMessage
	Payload       isWebSocketMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketMessage) Reset() {
	*x = WebSocketMessage{}
	mi := &file_market_data_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketMessage) ProtoMessage() {}

func (x *WebSocketMessage) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketMessage.ProtoReflect.Descriptor instead.
func (*WebSocketMessage) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{13}
}

func (x *WebSocketMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WebSocketMessage) GetPayload() isWebSocketMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WebSocketMessage) GetTickerBatch() *TickerBatch {
	if x != nil {
		if x, ok := x.Payload.(*WebSocketMessage_TickerBatch); ok {
			return x.TickerBatch
		}
	}
	return nil
}

func (x *WebSocketMessage) GetTicker() *TickerUpdate {
	if x != nil {
		if x, ok := x.Payload.(*WebSocketMessage_Ticker); ok {
			return x.Ticker
		}
	}
	return nil
}

func (x *WebSocketMessage) GetKlineUpdate() *WsKlineUpdate {
	if x != nil {
		if x, ok := x.Payload.(*WebSocketMessage_KlineUpdate); ok {
			return x.KlineUpdate
		}
	}
	return nil
}

func (x *WebSocketMessage) GetSortUpdate() *SortUpdate {
	if x != nil {
		if x, ok := x.Payload.(*WebSocketMessage_SortUpdate); ok {
			return x.SortUpdate
		}
	}
	return nil
}

func (x *WebSocketMessage) GetErrorMessage() *ErrorMessage {
	if x != nil {
		if x, ok := x.Payload.(*WebSocketMessage_ErrorMessage); ok {
			return x.ErrorMessage
		}
	}
	return nil
}

func (x *WebSocketMessage) GetInstrumentList() *InstrumentListUpdate {
	if x != nil {
		if x, ok := x.Payload.(*WebSocketMessage_InstrumentList); ok {
			return x.InstrumentList
		}
	}
	return nil
}

func (x *WebSocketMessage) GetInstrumentStatusUpdate() *InstrumentUpdate {
	if x != nil {
		if x, ok := x.Payload.(*WebSocketMessage_InstrumentStatusUpdate); ok {
			return x.InstrumentStatusUpdate
		}
	}
	return nil
}

func (x *WebSocketMessage) GetInstrumentMetadata() *CryptoInstrumentMetadata {
	if x != nil {
		if x, ok := x.Payload.(*WebSocketMessage_InstrumentMetadata); ok {
			return x.InstrumentMetadata
		}
	}
	return nil
}

func (x *WebSocketMessage) GetInstrumentTradingList() *CryptoInstrumentTradingArray {
	if x != nil {
		if x, ok := x.Payload.(*WebSocketMessage_InstrumentTradingList); ok {
			return x.InstrumentTradingList
		}
	}
	return nil
}

func (x *WebSocketMessage) GetAlertMessage() *AlertMessage {
	if x != nil {
		if x, ok := x.Payload.(*WebSocketMessage_AlertMessage); ok {
			return x.AlertMessage
		}
	}
	return nil
}

type isWebSocketMessage_Payload interface {
	isWebSocketMessage_Payload()
}

type WebSocketMessage_TickerBatch struct {
	// 批量更新多个币种的ticker 价格数据
	TickerBatch *TickerBatch `protobuf:"bytes,2,opt,name=ticker_batch,json=tickerBatch,proto3,oneof"`
}

type WebSocketMessage_Ticker struct {
	// 更新1个币种的ticker 价格数据
	Ticker *TickerUpdate `protobuf:"bytes,3,opt,name=ticker,proto3,oneof"`
}

type WebSocketMessage_KlineUpdate struct {
	// 更新k线数据
	KlineUpdate *WsKlineUpdate `protobuf:"bytes,4,opt,name=kline_update,json=klineUpdate,proto3,oneof"`
}

type WebSocketMessage_SortUpdate struct {
	// 更新已排序的币种列表
	SortUpdate *SortUpdate `protobuf:"bytes,5,opt,name=sort_update,json=sortUpdate,proto3,oneof"`
}

type WebSocketMessage_ErrorMessage struct {
	// 错误消息
	ErrorMessage *ErrorMessage `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3,oneof"`
}

type WebSocketMessage_InstrumentList struct {
	// 交易对列表更新，数据是排序过的
	InstrumentList *InstrumentListUpdate `protobuf:"bytes,7,opt,name=instrument_list,json=instrumentList,proto3,oneof"`
}

type WebSocketMessage_InstrumentStatusUpdate struct {
	// 交易对更新，包括上新和下架
	InstrumentStatusUpdate *InstrumentUpdate `protobuf:"bytes,8,opt,name=instrument_status_update,json=instrumentStatusUpdate,proto3,oneof"`
}

type WebSocketMessage_InstrumentMetadata struct {
	// 币种愿数据
	InstrumentMetadata *CryptoInstrumentMetadata `protobuf:"bytes,9,opt,name=instrument_metadata,json=instrumentMetadata,proto3,oneof"`
}

type WebSocketMessage_InstrumentTradingList struct {
	// 包含币种和最新价格的交易信息集合
	InstrumentTradingList *CryptoInstrumentTradingArray `protobuf:"bytes,10,opt,name=instrument_trading_list,json=instrumentTradingList,proto3,oneof"`
}

type WebSocketMessage_AlertMessage struct {
	// 提醒/通知消息
	AlertMessage *AlertMessage `protobuf:"bytes,11,opt,name=alert_message,json=alertMessage,proto3,oneof"`
}

func (*WebSocketMessage_TickerBatch) isWebSocketMessage_Payload() {}

func (*WebSocketMessage_Ticker) isWebSocketMessage_Payload() {}

func (*WebSocketMessage_KlineUpdate) isWebSocketMessage_Payload() {}

func (*WebSocketMessage_SortUpdate) isWebSocketMessage_Payload() {}

func (*WebSocketMessage_ErrorMessage) isWebSocketMessage_Payload() {}

func (*WebSocketMessage_InstrumentList) isWebSocketMessage_Payload() {}

func (*WebSocketMessage_InstrumentStatusUpdate) isWebSocketMessage_Payload() {}

func (*WebSocketMessage_InstrumentMetadata) isWebSocketMessage_Payload() {}

func (*WebSocketMessage_InstrumentTradingList) isWebSocketMessage_Payload() {}

func (*WebSocketMessage_AlertMessage) isWebSocketMessage_Payload() {}

// 内嵌 K 线详细数据
type WsKlineUpdate_KlineData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // K线起始时间 (毫秒级)
	Open          string                 `protobuf:"bytes,2,opt,name=open,proto3" json:"open,omitempty"`
	Close         string                 `protobuf:"bytes,3,opt,name=close,proto3" json:"close,omitempty"`
	High          string                 `protobuf:"bytes,4,opt,name=high,proto3" json:"high,omitempty"`
	Low           string                 `protobuf:"bytes,5,opt,name=low,proto3" json:"low,omitempty"`
	Vol           string                 `protobuf:"bytes,6,opt,name=vol,proto3" json:"vol,omitempty"`                     // 成交量 (币为单位)
	VolCcy        string                 `protobuf:"bytes,7,opt,name=vol_ccy,json=volCcy,proto3" json:"vol_ccy,omitempty"` // 成交额 (计价币为单位)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WsKlineUpdate_KlineData) Reset() {
	*x = WsKlineUpdate_KlineData{}
	mi := &file_market_data_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WsKlineUpdate_KlineData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WsKlineUpdate_KlineData) ProtoMessage() {}

func (x *WsKlineUpdate_KlineData) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WsKlineUpdate_KlineData.ProtoReflect.Descriptor instead.
func (*WsKlineUpdate_KlineData) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{2, 0}
}

func (x *WsKlineUpdate_KlineData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *WsKlineUpdate_KlineData) GetOpen() string {
	if x != nil {
		return x.Open
	}
	return ""
}

func (x *WsKlineUpdate_KlineData) GetClose() string {
	if x != nil {
		return x.Close
	}
	return ""
}

func (x *WsKlineUpdate_KlineData) GetHigh() string {
	if x != nil {
		return x.High
	}
	return ""
}

func (x *WsKlineUpdate_KlineData) GetLow() string {
	if x != nil {
		return x.Low
	}
	return ""
}

func (x *WsKlineUpdate_KlineData) GetVol() string {
	if x != nil {
		return x.Vol
	}
	return ""
}

func (x *WsKlineUpdate_KlineData) GetVolCcy() string {
	if x != nil {
		return x.VolCcy
	}
	return ""
}

var File_market_data_proto protoreflect.FileDescriptor

const file_market_data_proto_rawDesc = "" +
	"\n" +
	"\x11market_data.proto\x12\n" +
	"marketdata\"\xd9\x02\n" +
	"\fTickerUpdate\x12\x17\n" +
	"\ainst_id\x18\x01 \x01(\tR\x06instId\x12\x1d\n" +
	"\n" +
	"last_price\x18\x02 \x01(\tR\tlastPrice\x12\x17\n" +
	"\avol_24h\x18\x03 \x01(\tR\x06vol24h\x12\x1e\n" +
	"\vvol_ccy_24h\x18\x04 \x01(\tR\tvolCcy24h\x12\x19\n" +
	"\bhigh_24h\x18\x05 \x01(\tR\ahigh24h\x12\x17\n" +
	"\alow_24h\x18\x06 \x01(\tR\x06low24h\x12\x19\n" +
	"\bopen_24h\x18\a \x01(\tR\aopen24h\x12\x1d\n" +
	"\n" +
	"change_24h\x18\b \x01(\x01R\tchange24h\x12\x15\n" +
	"\x06ask_px\x18\t \x01(\tR\x05askPx\x12\x15\n" +
	"\x06ask_sz\x18\n" +
	" \x01(\tR\x05askSz\x12\x15\n" +
	"\x06bid_px\x18\v \x01(\tR\x05bidPx\x12\x15\n" +
	"\x06bid_sz\x18\f \x01(\tR\x05bidSz\x12\x0e\n" +
	"\x02ts\x18\r \x01(\x03R\x02ts\"A\n" +
	"\vTickerBatch\x122\n" +
	"\atickers\x18\x01 \x03(\v2\x18.marketdata.TickerUpdateR\atickers\"\xc3\x02\n" +
	"\rWsKlineUpdate\x12\x17\n" +
	"\ainst_id\x18\x01 \x01(\tR\x06instId\x12\x1f\n" +
	"\vtime_period\x18\x02 \x01(\tR\n" +
	"timePeriod\x12\x18\n" +
	"\aconfirm\x18\x03 \x01(\bR\aconfirm\x127\n" +
	"\x04data\x18\x04 \x01(\v2#.marketdata.WsKlineUpdate.KlineDataR\x04data\x1a\xa4\x01\n" +
	"\tKlineData\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04open\x18\x02 \x01(\tR\x04open\x12\x14\n" +
	"\x05close\x18\x03 \x01(\tR\x05close\x12\x12\n" +
	"\x04high\x18\x04 \x01(\tR\x04high\x12\x10\n" +
	"\x03low\x18\x05 \x01(\tR\x03low\x12\x10\n" +
	"\x03vol\x18\x06 \x01(\tR\x03vol\x12\x17\n" +
	"\avol_ccy\x18\a \x01(\tR\x06volCcy\"\x97\x01\n" +
	"\fErrorMessage\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x126\n" +
	"\x04data\x18\x02 \x03(\v2\".marketdata.ErrorMessage.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\">\n" +
	"\x14InstrumentListUpdate\x12&\n" +
	"\x0fsorted_inst_ids\x18\x01 \x03(\tR\rsortedInstIds\"n\n" +
	"\x10InstrumentUpdate\x12'\n" +
	"\x0fnew_instruments\x18\x01 \x03(\tR\x0enewInstruments\x121\n" +
	"\x14delisted_instruments\x18\x02 \x03(\tR\x13delistedInstruments\"\x9d\x01\n" +
	"\x0eCryptoExchange\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12!\n" +
	"\fapi_endpoint\x18\x05 \x01(\tR\vapiEndpoint\x12\x18\n" +
	"\acountry\x18\x06 \x01(\tR\acountry\"M\n" +
	"\n" +
	"SortUpdate\x12\x17\n" +
	"\asort_by\x18\x01 \x01(\tR\x06sortBy\x12&\n" +
	"\x0fsorted_inst_ids\x18\x02 \x03(\tR\rsortedInstIds\"Q\n" +
	"\tCryptoTag\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\xb3\x01\n" +
	"\x1bCryptoInstrumentTradingItem\x12U\n" +
	"\x13instrument_metadata\x18\x01 \x01(\v2$.marketdata.CryptoInstrumentMetadataR\x12instrumentMetadata\x12=\n" +
	"\rticker_update\x18\x02 \x01(\v2\x18.marketdata.TickerUpdateR\ftickerUpdate\"[\n" +
	"\x1cCryptoInstrumentTradingArray\x12;\n" +
	"\x04data\x18\x03 \x03(\v2'.marketdata.CryptoInstrumentTradingItemR\x04data\"\xab\x03\n" +
	"\x18CryptoInstrumentMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12#\n" +
	"\rinstrument_id\x18\x02 \x01(\tR\finstrumentId\x12\x1f\n" +
	"\vexchange_id\x18\x03 \x01(\rR\n" +
	"exchangeId\x12\x19\n" +
	"\bbase_ccy\x18\x04 \x01(\tR\abaseCcy\x12\x1b\n" +
	"\tquote_ccy\x18\x05 \x01(\tR\bquoteCcy\x12\x17\n" +
	"\aname_cn\x18\x06 \x01(\tR\x06nameCn\x12\x17\n" +
	"\aname_en\x18\a \x01(\tR\x06nameEn\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12'\n" +
	"\x0fprice_precision\x18\t \x01(\tR\x0epricePrecision\x12#\n" +
	"\rqty_precision\x18\n" +
	" \x01(\tR\fqtyPrecision\x12\x1d\n" +
	"\n" +
	"market_cap\x18\v \x01(\x04R\tmarketCap\x12\x1f\n" +
	"\vis_contract\x18\f \x01(\bR\n" +
	"isContract\x12)\n" +
	"\x04tags\x18\r \x03(\v2\x15.marketdata.CryptoTagR\x04tags\"\xc6\x03\n" +
	"\fAlertMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x16\n" +
	"\x06symbol\x18\x04 \x01(\tR\x06symbol\x12,\n" +
	"\x05level\x18\x05 \x01(\x0e2\x16.marketdata.AlertLevelR\x05level\x124\n" +
	"\n" +
	"alert_type\x18\x06 \x01(\x0e2\x15.marketdata.AlertTypeR\talertType\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12\x17\n" +
	"\auser_id\x18\b \x01(\tR\x06userId\x12'\n" +
	"\x0fsubscription_id\x18\n" +
	" \x01(\tR\x0esubscriptionId\x12\x1f\n" +
	"\vrelated_url\x18\v \x01(\tR\n" +
	"relatedUrl\x129\n" +
	"\x05extra\x18\t \x03(\v2#.marketdata.AlertMessage.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\f\x10\x14\"\x84\x06\n" +
	"\x10WebSocketMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12<\n" +
	"\fticker_batch\x18\x02 \x01(\v2\x17.marketdata.TickerBatchH\x00R\vtickerBatch\x122\n" +
	"\x06ticker\x18\x03 \x01(\v2\x18.marketdata.TickerUpdateH\x00R\x06ticker\x12>\n" +
	"\fkline_update\x18\x04 \x01(\v2\x19.marketdata.WsKlineUpdateH\x00R\vklineUpdate\x129\n" +
	"\vsort_update\x18\x05 \x01(\v2\x16.marketdata.SortUpdateH\x00R\n" +
	"sortUpdate\x12?\n" +
	"\rerror_message\x18\x06 \x01(\v2\x18.marketdata.ErrorMessageH\x00R\ferrorMessage\x12K\n" +
	"\x0finstrument_list\x18\a \x01(\v2 .marketdata.InstrumentListUpdateH\x00R\x0einstrumentList\x12X\n" +
	"\x18instrument_status_update\x18\b \x01(\v2\x1c.marketdata.InstrumentUpdateH\x00R\x16instrumentStatusUpdate\x12W\n" +
	"\x13instrument_metadata\x18\t \x01(\v2$.marketdata.CryptoInstrumentMetadataH\x00R\x12instrumentMetadata\x12b\n" +
	"\x17instrument_trading_list\x18\n" +
	" \x01(\v2(.marketdata.CryptoInstrumentTradingArrayH\x00R\x15instrumentTradingList\x12?\n" +
	"\ralert_message\x18\v \x01(\v2\x18.marketdata.AlertMessageH\x00R\falertMessageB\t\n" +
	"\apayload*U\n" +
	"\n" +
	"AlertLevel\x12\x14\n" +
	"\x10ALERT_LEVEL_INFO\x10\x00\x12\x17\n" +
	"\x13ALERT_LEVEL_WARNING\x10\x01\x12\x18\n" +
	"\x14ALERT_LEVEL_CRITICAL\x10\x02*\xb0\x01\n" +
	"\tAlertType\x12\x15\n" +
	"\x11ALERT_TYPE_SYSTEM\x10\x00\x12\x14\n" +
	"\x10ALERT_TYPE_PRICE\x10\x01\x12\x17\n" +
	"\x13ALERT_TYPE_STRATEGY\x10\x02\x12\x15\n" +
	"\x11ALERT_TYPE_CUSTOM\x10\x03\x12\x16\n" +
	"\x12ALERT_TYPE_LISTING\x10\x04\x12\x17\n" +
	"\x13ALERT_TYPE_ON_CHAIN\x10\x05\x12\x15\n" +
	"\x11ALERT_TYPE_SOCIAL\x10\x06B\x0fZ\r./protobuf;pbb\x06proto3"

var (
	file_market_data_proto_rawDescOnce sync.Once
	file_market_data_proto_rawDescData []byte
)

func file_market_data_proto_rawDescGZIP() []byte {
	file_market_data_proto_rawDescOnce.Do(func() {
		file_market_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_market_data_proto_rawDesc), len(file_market_data_proto_rawDesc)))
	})
	return file_market_data_proto_rawDescData
}

var file_market_data_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_market_data_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_market_data_proto_goTypes = []any{
	(AlertLevel)(0),                      // 0: marketdata.AlertLevel
	(AlertType)(0),                       // 1: marketdata.AlertType
	(*TickerUpdate)(nil),                 // 2: marketdata.TickerUpdate
	(*TickerBatch)(nil),                  // 3: marketdata.TickerBatch
	(*WsKlineUpdate)(nil),                // 4: marketdata.WsKlineUpdate
	(*ErrorMessage)(nil),                 // 5: marketdata.ErrorMessage
	(*InstrumentListUpdate)(nil),         // 6: marketdata.InstrumentListUpdate
	(*InstrumentUpdate)(nil),             // 7: marketdata.InstrumentUpdate
	(*CryptoExchange)(nil),               // 8: marketdata.CryptoExchange
	(*SortUpdate)(nil),                   // 9: marketdata.SortUpdate
	(*CryptoTag)(nil),                    // 10: marketdata.CryptoTag
	(*CryptoInstrumentTradingItem)(nil),  // 11: marketdata.CryptoInstrumentTradingItem
	(*CryptoInstrumentTradingArray)(nil), // 12: marketdata.CryptoInstrumentTradingArray
	(*CryptoInstrumentMetadata)(nil),     // 13: marketdata.CryptoInstrumentMetadata
	(*AlertMessage)(nil),                 // 14: marketdata.AlertMessage
	(*WebSocketMessage)(nil),             // 15: marketdata.WebSocketMessage
	(*WsKlineUpdate_KlineData)(nil),      // 16: marketdata.WsKlineUpdate.KlineData
	nil,                                  // 17: marketdata.ErrorMessage.DataEntry
	nil,                                  // 18: marketdata.AlertMessage.ExtraEntry
}
var file_market_data_proto_depIdxs = []int32{
	2,  // 0: marketdata.TickerBatch.tickers:type_name -> marketdata.TickerUpdate
	16, // 1: marketdata.WsKlineUpdate.data:type_name -> marketdata.WsKlineUpdate.KlineData
	17, // 2: marketdata.ErrorMessage.data:type_name -> marketdata.ErrorMessage.DataEntry
	13, // 3: marketdata.CryptoInstrumentTradingItem.instrument_metadata:type_name -> marketdata.CryptoInstrumentMetadata
	2,  // 4: marketdata.CryptoInstrumentTradingItem.ticker_update:type_name -> marketdata.TickerUpdate
	11, // 5: marketdata.CryptoInstrumentTradingArray.data:type_name -> marketdata.CryptoInstrumentTradingItem
	10, // 6: marketdata.CryptoInstrumentMetadata.tags:type_name -> marketdata.CryptoTag
	0,  // 7: marketdata.AlertMessage.level:type_name -> marketdata.AlertLevel
	1,  // 8: marketdata.AlertMessage.alert_type:type_name -> marketdata.AlertType
	18, // 9: marketdata.AlertMessage.extra:type_name -> marketdata.AlertMessage.ExtraEntry
	3,  // 10: marketdata.WebSocketMessage.ticker_batch:type_name -> marketdata.TickerBatch
	2,  // 11: marketdata.WebSocketMessage.ticker:type_name -> marketdata.TickerUpdate
	4,  // 12: marketdata.WebSocketMessage.kline_update:type_name -> marketdata.WsKlineUpdate
	9,  // 13: marketdata.WebSocketMessage.sort_update:type_name -> marketdata.SortUpdate
	5,  // 14: marketdata.WebSocketMessage.error_message:type_name -> marketdata.ErrorMessage
	6,  // 15: marketdata.WebSocketMessage.instrument_list:type_name -> marketdata.InstrumentListUpdate
	7,  // 16: marketdata.WebSocketMessage.instrument_status_update:type_name -> marketdata.InstrumentUpdate
	13, // 17: marketdata.WebSocketMessage.instrument_metadata:type_name -> marketdata.CryptoInstrumentMetadata
	12, // 18: marketdata.WebSocketMessage.instrument_trading_list:type_name -> marketdata.CryptoInstrumentTradingArray
	14, // 19: marketdata.WebSocketMessage.alert_message:type_name -> marketdata.AlertMessage
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_market_data_proto_init() }
func file_market_data_proto_init() {
	if File_market_data_proto != nil {
		return
	}
	file_market_data_proto_msgTypes[13].OneofWrappers = []any{
		(*WebSocketMessage_TickerBatch)(nil),
		(*WebSocketMessage_Ticker)(nil),
		(*WebSocketMessage_KlineUpdate)(nil),
		(*WebSocketMessage_SortUpdate)(nil),
		(*WebSocketMessage_ErrorMessage)(nil),
		(*WebSocketMessage_InstrumentList)(nil),
		(*WebSocketMessage_InstrumentStatusUpdate)(nil),
		(*WebSocketMessage_InstrumentMetadata)(nil),
		(*WebSocketMessage_InstrumentTradingList)(nil),
		(*WebSocketMessage_AlertMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_market_data_proto_rawDesc), len(file_market_data_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_market_data_proto_goTypes,
		DependencyIndexes: file_market_data_proto_depIdxs,
		EnumInfos:         file_market_data_proto_enumTypes,
		MessageInfos:      file_market_data_proto_msgTypes,
	}.Build()
	File_market_data_proto = out.File
	file_market_data_proto_goTypes = nil
	file_market_data_proto_depIdxs = nil
}
